### ISSUE TITLE
Color picker isn't showing up when I click on a color. Only the native VS Code picker does. 

### ISSUE THREAD

**Issue by fmotion1** [jeronimoek/color-picker-universal#97] opened 2023-11-06 22:50 UTC
All the other settings are working, if I access them from the command palette. I can get the picker to show up if I click here:

![Code_1Uop6jQsmt](https://github.com/jeronimoek/color-picker-universal/assets/33441569/88fd1fd6-108b-4212-a3db-fa65a30953b1)

But unfortunately, it doesn't work if I click on a color. I'm also getting double color decorators too. 

![Code_wugQuNVWpW](https://github.com/jeronimoek/color-picker-universal/assets/33441569/68635323-0239-4c95-ac6e-c6a7d49ad45b)

Here's a screen recording:

https://github.com/jeronimoek/color-picker-universal/assets/33441569/ae92b02e-f5bd-4ae6-bbdc-ec7aaad33b1e

Any help or assistance would be greatly appreciated!

**Comment by jeronimoek** [comment] 2023-11-09 01:13
Could this be a duplicate of #68 ?

**Comment by jeronimoek** [comment] 2023-12-08 01:14
Do you know if this problem still exists? If so, please share with me your VSC version and OS. You can see that in the "help" window.
I'm quite lost here since on my computer I only see one color picker in the .json files, the color picker duplicated only happens in CSS less scss or sass files

**Comment by jeronimoek** [comment] 2024-03-14 11:50
Can't reproduce

**Closed by jeronimoek** 2024-03-14 11:50 UTC
Labels: bug
